[package]
name = "unicorn_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicorn-engine = {git = 'https://github.com/lg3696/unicorn', branch = 'fix-memory-leak'}
# unicorn-engine = "2.0.1"
elf = "0.7.0"
log = "0.4.17" 
env_logger = "0.10.0"
capstone = "0.11.0"
indicatif = "0.17.2"
git-version = "0.3.5"
rayon = "1.6.1"
